# Unit 2 task

This Jupyter notebook is a template for this week's assignment. You should fill in the blank code and text cells below to answer the questions, and upload your completed notebook to Moodle for marking.

Remember to:
* print out the results of each calculation;
* where you are asked to complete text cells, make sure you use complete, grammatically correct sentences.

Make sure you run the cell below to import the NumPy package.

In [2]:
import numpy as np

## Part 1

### (a)

The following statement creates an array of evenly spaced values:

    np.array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

Use an appropriate NumPy function in the next cell to create an array containing the same values in a more efficient way, and assign this to a variable called `array_a`.

In [3]:
### STUDENT CODE CELL

array_a = np.linspace(0.5, 3, 6)
array_a

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

### (b)

The following statement creates an array of evenly spaced **integers**: 

    array([ 5, 10, 15, 20, 25, 30])

Again, use an appropriate NumPy function in the next cell to create an array containing the same values in a more efficient way, and assign this to a variable called `array_b`.

In [4]:
### STUDENT CODE CELL

array_b = np.arange(5, 35, 5)
array_b

array([ 5, 10, 15, 20, 25, 30])

### (c)

Multiply the values in `array_a` and `array_b` together, assigning the results to a variable `array_c`.

In [5]:
### STUDENT CODE CELL

array_c = array_a * array_b
array_c

### (d)

Use array slicing to create an array `array_d` containing the elements from `array_c` but omitting the first and last elements.

In [6]:
### STUDENT CODE CELL

array_d = array_c[1:-1]
array_d

array([10. , 22.5, 40. , 62.5])

# (e)

Use your web searching skills to find NumPy functions that will calculate the dot product and the cross product of two vectors. Use these functions to calculate both products for the vectors (0.3, 0.4, 1.2) and (0.4, -0.3, 1.2).

In [7]:
### STUDENT CODE CELL

A = (0.3, 0.4, 1.2)
B = (0.4, -0.3, 1.2)
np.dot(A, B)
np.cross(A, B)

print(np.dot(A, B))
print(np.cross(A, B))

1.44
[ 0.84  0.12 -0.25]


### (f)

The for loop is useful when you need to deal with each element of an array in turn, but it can be slow compared to more specialized NumPy functions. In two separate code cells below, you should try adding together the contents of the array `data` in two different ways: 
- using a loop;
- using the function `np.sum`.

The `%%time` function (a Jupyter "magic" function, not part of Python) will tell you how long each takes. You may need to adjust the size of the array to get useful results.

Use the following text cell to comment on the results.

In [8]:
# Depending on the speed of your computer, you may want to vary the size of this array.
# Remember that you can interrupt the kernel if a calculation is taking too long!  

data = np.ones(10000)


In [28]:
%%time
### STUDENT CODE CELL

sum = 0.

# Add a loop here to add each element of data in turn to "sum".
for value in data:
    sum += value
print(f"The sum is {sum}")

The sum is 4996.0
CPU times: total: 15.6 ms
Wall time: 2 ms


In [29]:
%%time
### STUDENT CODE CELL

sum = 0. # Replace this line with a call to the np.sum function.

np.sum(data)

print(f"The sum is {sum}")

The sum is 0.0
CPU times: total: 0 ns
Wall time: 0 ns


##### STUDENT TEXT CELL: add to this text cell to comment on the results of timing the two different ways of carrying out the same calculation.

The timing using the sum function instead of using a loop seems to be 50% slower initially. However figures are given both to 1 s.f. so so we can't accurately confirm this without some greater precision of the times. 

## Part 2:

For this part of the task you will be working with the "wheat spike" example you saw in the first PHAS0007 "Data Analysis and Statistics" lecture, and use Python to reproduce some of the calculations you saw there.

You'll probably want to consult the lecture slides on Dr Llorente Garcia's Moodle as well as the PHAS0007 Data Analysis Booklet.

Download the file `wheatdata.txt` from Moodle and save it in the same directory as your Notebook. This data file contains the same data as on slide 11 of the lecture slides.

### (a)

Use the code cell below to do the following:-
- Import the data from this file into an array using `np.loadtxt()`: choose your own (sensible) variable name for this array.
- Print out the array with an appropriate text string.

In [30]:
### STUDENT CODE CELL

data = np.loadtxt('wheatdata.txt')
print(f'Data for number of spikes is {data}')


Data for number of spikes is [533. 440. 484. 446. 474. 492. 512. 515. 528. 572.]


### (b)

Using information from the data analysis booklet or elsewhere, find the appropriate NumPy function to calculate the mean number of spikes in each patch. Calculate this in the cell below, and again, output this with an appropriate text string.

In [31]:
### STUDENT CODE CELL

mean = np.mean(data)
print(f'Mean number of wheat spikes is {mean}')

Mean number of wheat spikes is 499.6


### (c)

The formula for the (sample) standard deviation is 
$$ \sigma = \sqrt{\frac{\sum{(x_i - \bar{x})^2}}{N-1}}, $$

   where $N$ is the number of data points and $\bar{x}$ the average you just calculated. 
   
   Use the python function `len()` to calculate a value for $N$ in the cell below, and again, output this with an appropriate text string. Remember, you can use "SHIFT+TAB" with the cursor on a function name to view the documentation for that function.

In [32]:
### STUDENT CODE CELL

Number_of_data_points = len(data)
print(f'Number of data points is {Number_of_data_points}')

Number of data points is 10


### (d)

We're going to calculate the numerator of the equation for the standard deviation in steps. 

We can calculate the individual deviations $d_i = x_i - \bar{x}$ as in the code cell below. You will need to make sure that the variable names here match the variable names you've chosen above.

In [33]:
# Edit the variable names in this cell to match the variable names you have used above

deviations = data - mean                            # calculate individual deviations
print("The individual deviations from the mean are", deviations) # output this value with an appropriate text string

The individual deviations from the mean are [ 33.4 -59.6 -15.6 -53.6 -25.6  -7.6  12.4  15.4  28.4  72.4]


Note how this works: `spike_data` is an array of values, but `mean_spikes` is a single value. Numpy will automatically subtract `mean_spikes` from every element of the array `spike_data`.

### (e)

Now we have calculated the individual deviations, we can square them, then sum them together using `np.sum()`. Do this in the cell below. Make sure you do the squaring and summing  in the right order though!

Remember to print out the result with an appropriate text string.

In [34]:
### STUDENT CODE CELL

square_of_deviations = np.square(deviations)
sum_of_square_of_deviations = np.sum(square_of_deviations)

### STUDENT CODE CELL

Number_of_data_points = len(data)
print(f'The sum of the square of the deviations is {sum_of_square_of_deviations}')

The sum of the square of the deviations is 14936.400000000001


### (f)

Now you have all the elements you need to calculate the standard deviation using the equation in question 3 above. Do this in the cell below. You should find your answer is close to (but not exactly the same as) the standard deviation calculated in the lecture slides. 

Remember to print out the result with an appropriate text string. Yes, you will always need to do this.

In [35]:
### STUDENT CODE CELL

standard_deviation = ((sum_of_square_of_deviations)/(Number_of_data_points - 1))**(.5)
print(f'The standard deviation is {standard_deviation}')

The standard deviation is 40.738188472243095


That was rather an effort to calculate the standard deviation, and fortunately numpy has a function that will do this for you: `np.std()`.

You do have to be a bit careful with this function, and you're about to see why. Run the cell below, compare the results to what you just calculated above, then read both the [documentation for `np.std()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.std.html) and the information in section 2.6 (p.13) of [Hughes and Hase](https://ebookcentral.proquest.com/lib/ucl/reader.action?docID=584562&ppg=25.) (You may need to sign in with your UCL credentials to access this link).

### (g)

Then use the text cell below to state which version of the standard deviation you should use here, and (briefly) why.

In [36]:
stdev_1 = np.std(data)          # Edit to reflect your chosen variable names
stdev_2 = np.std(data, ddof=1)  # Edit to reflect your chosen variable names

print("Standard deviation: first calculation gives", stdev_1, ", second calculation gives", stdev_2)

Standard deviation: first calculation gives 38.647638996451 , second calculation gives 40.738188472243095


##### STUDENT TEXT CELL: add to this text cell to answer question (g)

I would use the second version as the mean of the data points were determined from the same data set instead of being independantly determined, so we can have one less degree of freedom and take away 1 from N in the denominator of the equation.

### (h)

We can also calculate the standard error of the mean, which is given by 
$$\alpha = \frac{\sigma_{(N-1)}}{\sqrt{N}}$$
Apply what you've learned above to calculate this in the cell below. 

In [37]:
### STUDENT CODE CELL

standard_error = (standard_deviation/(Number_of_data_points)**(.5))
print(f'Standard error of the mean is {standard_error}')

#The (n-1) part looks like its part of the equation when its actually a subscript. A lot of time was wasted before figuring this out

Standard error of the mean is 12.882546332150334


### (i)

Finally, use your web-searching skills to find a Python function that will calculate the standard error of the mean for you, and verify that you get the same result when using this function. (Hint: this function is not in NumPy, so you will need to import another package!)

In [26]:
### STUDENT CODE CELL

from scipy.stats import sem

standard_error_2 = sem(data)

print(f'Standard error of the mean is {standard_error_2}, which agrees with the previous calculation')

Standard error of the mean is 12.882546332150334, which agrees with the previous calculation
